/// Flutter icons ScoutingIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ScoutingIcons
///      fonts:
///       - asset: fonts/ScoutingIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ScoutingIcons {
  ScoutingIcons._();

  static const _kFontFam = 'ScoutingIcons';
  static const _kFontPkg = null;

  static const IconData down_arrow = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boolean = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_button = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData counter = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radioactive = IconData(0xea79, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sliders = IconData(0xf1de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData divider = IconData(0xf7a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
